/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ./public/models/room-scene/basic-scene.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/basic-scene.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.World_Ground.geometry} material={nodes.World_Ground.material} scale={7.91} />
      <mesh geometry={nodes.Floor.geometry} material={nodes.Floor.material} position={[0, 0.032, 0.05]} scale={[2, 0.034, 2]} />
      <mesh geometry={nodes.Floor_Plamks.geometry} material={nodes.Floor_Plamks.material} position={[0, 0, 0.05]} scale={2} />
      <mesh geometry={nodes.Living_Wall.geometry} material={nodes.Living_Wall.material} position={[-2.067, 0.998, -0.05]} scale={[4, 2, 2]} />
      <mesh geometry={nodes.Setup_Wall.geometry} material={nodes.Setup_Wall.material} position={[0.603, 1.137, -2.044]} scale={[1, 1, 2]} />
      <mesh geometry={nodes.Carpet.geometry} material={nodes.Carpet.material} position={[0, 0.087, 0.371]} scale={[0.702, 0.617, 0.971]} />
      <mesh geometry={nodes.Bean_Bag.geometry} material={nodes.Bean_Bag.material} position={[1.313, 0.283, -1.434]} rotation={[0, -0.382, 0]} scale={0.562} />
      <mesh geometry={nodes.Sofa.geometry} material={nodes.Sofa.material} position={[1.44, 0.211, 0.449]} rotation={[0, -Math.PI / 2, 0]} scale={[0.752, 0.792, 0.792]} />
      <mesh geometry={nodes.Coffee_Table001.geometry} material={nodes.Coffee_Table001.material} position={[0.024, 0.105, 0.426]} rotation={[Math.PI, 0, Math.PI]} scale={[0.307, 0.168, 0.022]} />
      <mesh geometry={nodes.Tv_Cabinet.geometry} material={nodes.Tv_Cabinet.material} position={[-1.723, 0.106, 0.391]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Cabinet1.geometry} material={nodes.Cabinet1.material} position={[-0.9, 0.01, -0.184]} />
        <mesh geometry={nodes.Cabinet1_Door.geometry} material={nodes.Cabinet1_Door.material} position={[-0.6, 0.086, 0.176]} />
        <mesh geometry={nodes.legs003.geometry} material={nodes.legs003.material} position={[-0.762, -0.032, -0.139]} rotation={[0.155, 0, -0.235]} scale={[0.014, 0.037, 0.014]} />
      </mesh>
      <mesh geometry={nodes.Floor_Plant.geometry} material={nodes.Floor_Plant.material} position={[-1.847, 0.087, 1.693]} rotation={[-Math.PI, 1.202, -Math.PI]} />
      <mesh geometry={nodes.Cover001.geometry} material={nodes.Cover001.material} position={[0.389, 0.376, -1.665]} scale={1.123} />
      <mesh geometry={nodes.Drawers.geometry} material={nodes.Drawers.material} position={[-0.899, 0.396, -1.365]} scale={1.123} />
      <mesh geometry={nodes.Desk_Counter_Top.geometry} material={nodes.Desk_Counter_Top.material} position={[-0.257, 0.678, -1.622]} scale={[0.817, 0.852, 0.314]} />
      <mesh geometry={nodes.Cover002.geometry} material={nodes.Cover002.material} position={[-0.899, 0.384, -1.677]} scale={1.123} />
      <mesh geometry={nodes.Drawers002.geometry} material={nodes.Drawers002.material} position={[0.382, 0.395, -1.361]} scale={1.123} />
      <mesh geometry={nodes.Creative_Software_Solutions.geometry} material={nodes.Creative_Software_Solutions.material} position={[-2, 1.46, -0.036]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.26} />
    </group>
  )
}

useGLTF.preload('/basic-scene.glb')
