/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ./public/models/room-scene/newton-craddles.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/newton-craddles.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" position={[-0.941, 0.747, -1.701]} rotation={[-Math.PI / 2, 0, -1.011]} scale={0.017}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="ball001_10" position={[0, 0, -2]}>
                <mesh name="Ball_2" geometry={nodes.Ball_2.geometry} material={nodes.Ball_2.material} position={[-0.001, 0.236, -0.001]} />
              </group>
              <group name="ball002_5" position={[0, 0, -4]}>
                <mesh name="Ball_3" geometry={nodes.Ball_3.geometry} material={nodes.Ball_3.material} position={[-0.001, 0.236, -0.001]} />
              </group>
              <group name="ball003_4" position={[0, 0, -6]}>
                <mesh name="Ball_4" geometry={nodes.Ball_4.geometry} material={nodes.Ball_4.material} position={[-0.001, 0.236, -0.001]} />
              </group>
              <group name="ball004_3" position={[0, 0, -8]}>
                <mesh name="Ball_5" geometry={nodes.Ball_5.geometry} material={nodes.Ball_5.material} position={[-0.001, 0.236, -0.001]} />
              </group>
              <group name="ball_12" position={[0, 2.008, 5.51]} rotation={[-0.699, 0, 0]}>
                <mesh name="Ball_1" geometry={nodes.Ball_1.geometry} material={nodes.Ball_1.material} position={[0, 0.234, 0]} />
              </group>
              <group name="thread001_9" position={[0, 1.039, -2]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh name="Thread_2" geometry={nodes.Thread_2.geometry} material={nodes.Thread_2.material} position={[-3.416, 0.027, -0.005]} />
              </group>
              <group name="thread002_8" position={[0, 1.039, -4]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh name="Thread_3" geometry={nodes.Thread_3.geometry} material={nodes.Thread_3.material} position={[-3.416, 0.027, -0.005]} />
              </group>
              <group name="thread003_7" position={[0, 1.039, -6]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh name="Thread_4" geometry={nodes.Thread_4.geometry} material={nodes.Thread_4.material} position={[-3.416, 0.027, -0.005]} />
              </group>
              <group name="thread004_6" position={[0, 1.039, -8]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh name="Thread_5" geometry={nodes.Thread_5.geometry} material={nodes.Thread_5.material} position={[-3.416, 0.027, -0.005]} />
              </group>
              <group name="thread_11" position={[0, 2.803, 4.842]} rotation={[-0.699, 0, -Math.PI / 2]}>
                <mesh name="Thread_1" geometry={nodes.Thread_1.geometry} material={nodes.Thread_1.material} position={[-3.416, 0.027, -0.005]} />
              </group>
              <group name="Base_2" position={[0, -1.727, -4]}>
                <mesh name="Base" geometry={nodes.Base.geometry} material={nodes.Base.material} position={[0.017, 0.017, -0.091]} />
              </group>
              <group name="Frame_1" position={[3.227, 8.565, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh name="Frame" geometry={nodes.Frame.geometry} material={nodes.Frame.material} position={[-3.227, -4, 0.31]} />
              </group>
              <group name="Thread_Fix_0" position={[3.413, 8.565, 0]} rotation={[0, 0, Math.PI / 2]}>
                <mesh name="Thread_points" geometry={nodes.Thread_points.geometry} material={nodes.Thread_points.material} position={[-0.001, 3.547, -4.15]} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/newton-craddles.glb')
